"""Add image_url to Item model

Revision ID: 65fe241c819c
Revises: d5c40fcc5cb9
Create Date: 2025-04-30 18:22:26.799211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65fe241c819c'
down_revision = 'd5c40fcc5cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
