"""Update Question and Answer models

Revision ID: a6ee2a3952c8
Revises: 65fe241c819c
Create Date: 2025-04-30 18:23:09.736035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ee2a3952c8'
down_revision = '65fe241c819c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('answer_text')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('question_text')
        batch_op.drop_column('is_answered')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_answered', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('question_text', sa.TEXT(), nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('status')
        batch_op.drop_column('content')
        batch_op.drop_column('title')

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_text', sa.TEXT(), nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
