"""add is_admin and is_customer_rep columns to users table

Revision ID: fe41bb8e7e41
Revises: 80bbab6a146a
Create Date: 2025-04-30 20:23:11.845217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe41bb8e7e41'
down_revision = '80bbab6a146a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('keywords',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('auction_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_customer_rep', sa.Boolean(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.drop_index('ix_users_email')
        batch_op.drop_index('ix_users_username')
        batch_op.create_unique_constraint('uq_users_email', ['email'])
        batch_op.create_unique_constraint('uq_users_username', ['username'])
        batch_op.drop_column('phone')
        batch_op.drop_column('role')
        batch_op.drop_column('first_name')
        batch_op.drop_column('address')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.create_index('ix_users_username', ['username'], unique=1)
        batch_op.create_index('ix_users_email', ['email'], unique=1)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('is_customer_rep')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('auction_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('keywords',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
